### ISSUE TITLE
Added not relevant page

### ISSUE THREAD

**Issue by d47081** [ygguser/simple_sites_directory#10]
Today I found in my RSS feed this website (hosted by YGGverse):

```
http://[201:23b4:991a:634d:8359:4521:5576:15b7]///
	
Welcome to nginx!
```

Maybe the crawler pushed the link?
How is it possible?

This page not in use at this moment, just document root for other services.

Anyway, [Yo](https://github.com/YGGverse/Yo/blob/main/src/cli/document/crawl.php) crawler works with links only, and also ignores links with `rel=nofollow` attribute. And this never happened before, maybe someone kidding there?

**Comment by ygguser** [comment]
> Even with /// path?

Maybe someone was just experimenting. There are no means of automatically adding addresses there now.

> Suppose, just good moment to check the access logs

It was probably a few months ago... Nothing terrible has happened since then...

> it has network crawler?

At the very beginning, when a simple network crawler could be used on the network, one worked here that collected node addresses and checked whether a web server was running on them. If there were any, they were added to the database automatically.
